### ISSUE TITLE
Create Account System / A Way To Save User's Purchases

### ISSUE THREAD

**Issue by ZacharyDavidSaunders** [Z-and-Z-Software/IT-Certification-Prep#10]
After a user makes a purchase, we need to a way to associate that purchase with a user so that a user may retrieve their purchases when using the app on another device. 

**There are various ways of handling this, but here are the most common approaches:**
1.  Identify a user via their Google Account. Find a way to save purchases to a user's Google Account.
2.  Create a login system that points to our own server / database.
3.  Utilize an OAuth system (Facebook, G+, etc.) and find a way to save purchases to a user's OAuth account.

**Comment by Zackazt** [comment]
Closing.  Google's API handles this.
