### ISSUE TITLE
Designing the user interface

### ISSUE THREAD

**Issue by Zackazt** [Z-and-Z-Software/IT-Certification-Prep#3]
Currently there is no user interface for the application.  The application should have a simple to understand, but elegant user interface.  This is the type of app where a user may spend medium to long periods of time looking at their phone screen so the color palette should be easy on the eyes.

Simple transitioning animations can make all of the difference in terms of aesthetically pleasing the user.  We should decide on a minimum API.  The higher the API, the more available features however the less people can use the application.

Sounds effects that are mellow and easy on the ears can also be beneficial.  Ambient background audio can also help the user focus.  The ability to mute the audio should be simple to find and quick to access, but not be on the main user interface itself.  We may want to create a custom media player class.

We could use a simple slide out menu for certain settings including audio, changing the color theme, accessing other activities, etc.  This can be achieved using Fragments.

**Comment by ZacharyDavidSaunders** [comment]
Closed as deprecated... A new issue will be created for this assignment.
