### ISSUE TITLE
Create Store Functionality That Allows Users To Purchase Exam Packs

### ISSUE THREAD

**Issue by ZacharyDavidSaunders** [Z-and-Z-Software/IT-Certification-Prep#9]
We need a way for users to purchase exam packs from within the app. 

All purchase related functions should be listed in the Store.java file.

**Links For Reference:**
https://developer.android.com/google/play/billing/billing_integrate.html
https://developer.android.com/google/play/billing/api.html
https://developer.android.com/google/play/billing/billing_testing.html

**Comment by Zackazt** [comment]
This may be directly tied with Issue #10.

**Comment by Zackazt** [comment]
Closing.  This has been moved to Issue-#17.
